// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameHistory = "history"

// History mapped from table <history>
type History struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Source      string `gorm:"column:source" json:"source"`
	Destination string `gorm:"column:destination" json:"destination"`
	Original    string `gorm:"column:original" json:"original"`
	Translation string `gorm:"column:translation" json:"translation"`
}

// TableName History's table name
func (*History) TableName() string {
	return TableNameHistory
}
