// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameNotice = "notices"

// Notice mapped from table <notices>
type Notice struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Userid    int32     `gorm:"column:userid" json:"userid"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	Status    string    `gorm:"column:status" json:"status"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
