// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskRunUser = "task_run_users"

// TaskRunUser mapped from table <task_run_users>
type TaskRunUser struct {
	ID         int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID     int       `gorm:"column:task_id" json:"task_id"`
	TaskRunID  int       `gorm:"column:task_run_id" json:"task_run_id"`
	UserID     int       `gorm:"column:user_id" json:"user_id"`
	Duration   int       `gorm:"column:duration" json:"duration"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	StartAt    time.Time `gorm:"column:start_at" json:"start_at"`
	FinishedAt time.Time `gorm:"column:finished_at" json:"finished_at"`
	Status     string    `gorm:"column:status" json:"status"`
}

// TableName TaskRunUser's table name
func (*TaskRunUser) TableName() string {
	return TableNameTaskRunUser
}
