// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskUserAudit = "task_user_audits"

// TaskUserAudit mapped from table <task_user_audits>
type TaskUserAudit struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Taskid      int32     `gorm:"column:taskid" json:"taskid"`
	Userid      int32     `gorm:"column:userid" json:"userid"`
	Audituserid int32     `gorm:"column:audituserid" json:"audituserid"`
	Createdat   time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Status      string    `gorm:"column:status" json:"status"`
	Reason      string    `gorm:"column:reason" json:"reason"`
}

// TableName TaskUserAudit's table name
func (*TaskUserAudit) TableName() string {
	return TableNameTaskUserAudit
}
