// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserTaskAudit = "task_user_audits"

// UserTaskAudit mapped from table <task_user_audits>
type UserTaskAudit struct {
	ID          int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID      int       `gorm:"column:task_id" json:"task_id"`
	UserID      int       `gorm:"column:user_id" json:"user_id"`
	AuditUserID int       `gorm:"column:audit_user_id" json:"audit_user_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	Status      string    `gorm:"column:status" json:"status"`
	Reason      string    `gorm:"column:reason" json:"reason"`
}

// TableName UserTaskAudit's table name
func (*UserTaskAudit) TableName() string {
	return TableNameUserTaskAudit
}
