// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserTask = "task_users"

// UserTask mapped from table <task_users>
type UserTask struct {
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID    int       `gorm:"column:task_id" json:"task_id"`
	UserID    int       `gorm:"column:user_id" json:"user_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	Status    string    `gorm:"column:status" json:"status"`
	Role      string    `gorm:"column:role" json:"role"`
}

// TableName UserTask's table name
func (*UserTask) TableName() string {
	return TableNameUserTask
}
