// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskRun = "task_runs"

// TaskRun mapped from table <task_runs>
type TaskRun struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Taskid    int32     `gorm:"column:taskid" json:"taskid"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Startat   time.Time `gorm:"column:startat" json:"startat"`
	Endat     time.Time `gorm:"column:endat" json:"endat"`
	Duration  string    `gorm:"column:duration" json:"duration"`
	Status    string    `gorm:"column:status" json:"status"`
}

// TableName TaskRun's table name
func (*TaskRun) TableName() string {
	return TableNameTaskRun
}
