// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskRunUser = "task_run_users"

// TaskRunUser mapped from table <task_run_users>
type TaskRunUser struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Taskid    int32     `gorm:"column:taskid" json:"taskid"`
	Taskrunid int32     `gorm:"column:taskrunid" json:"taskrunid"`
	Userid    int32     `gorm:"column:userid" json:"userid"`
	Duration  string    `gorm:"column:duration" json:"duration"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Startat   time.Time `gorm:"column:startat" json:"startat"`
	Endat     time.Time `gorm:"column:endat" json:"endat"`
}

// TableName TaskRunUser's table name
func (*TaskRunUser) TableName() string {
	return TableNameTaskRunUser
}
