// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskRunLog = "task_run_logs"

// TaskRunLog mapped from table <task_run_logs>
type TaskRunLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Taskid    int32     `gorm:"column:taskid" json:"taskid"`
	Taskrunid int32     `gorm:"column:taskrunid" json:"taskrunid"`
	Userid    int32     `gorm:"column:userid" json:"userid"`
	Content   string    `gorm:"column:content" json:"content"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Images    string    `gorm:"column:images" json:"images"`
	Videos    string    `gorm:"column:videos" json:"videos"`
}

// TableName TaskRunLog's table name
func (*TaskRunLog) TableName() string {
	return TableNameTaskRunLog
}
