// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskUser = "task_users"

// TaskUser mapped from table <task_users>
type TaskUser struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Taskid    int32     `gorm:"column:taskid" json:"taskid"`
	Userid    int32     `gorm:"column:userid" json:"userid"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Status    string    `gorm:"column:status" json:"status"`
	Role      string    `gorm:"column:role" json:"role"`
}

// TableName TaskUser's table name
func (*TaskUser) TableName() string {
	return TableNameTaskUser
}
