// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string         `gorm:"column:name;not null" json:"name"`
	CreateBy   int            `gorm:"column:create_by" json:"create_by"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at" swaggerignore:"true"`
	FinishedAt time.Time      `gorm:"column:finished_at" json:"finished_at" `
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at" swaggerignore:"true"`
	Describe   string         `gorm:"column:describe" json:"describe"`
	Require    string         `gorm:"column:require" json:"require"`
	Location   string         `gorm:"column:location" json:"location"`
	Status     string         `gorm:"column:status" json:"status"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
