// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTaskRun = "task_runs"

// TaskRun mapped from table <task_runs>
type TaskRun struct {
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TaskID    int       `gorm:"column:task_id" json:"task_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	StartAt   time.Time `gorm:"column:start_at" json:"start_at"`
	Endat     time.Time `gorm:"column:endat" json:"endat"`
	Duration  string    `gorm:"column:duration" json:"duration"`
	Status    string    `gorm:"column:status" json:"status"`
}

// TableName TaskRun's table name
func (*TaskRun) TableName() string {
	return TableNameTaskRun
}
