// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Createby  int32     `gorm:"column:createby" json:"createby"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Updatedat time.Time `gorm:"column:updatedat" json:"updatedat"`
	Endat     time.Time `gorm:"column:endat" json:"endat"`
	Deletedat time.Time `gorm:"column:deletedat" json:"deletedat"`
	Describe  string    `gorm:"column:describe" json:"describe"`
	Require   string    `gorm:"column:require" json:"require"`
	Status    string    `gorm:"column:status" json:"status"`
	Location  string    `gorm:"column:location;comment:发布任务的位置" json:"location"` // 发布任务的位置
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
