// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;not null" json:"username"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Email     string    `gorm:"column:email" json:"email"`
	Phone     string    `gorm:"column:phone" json:"phone"`
	Status    string    `gorm:"column:status" json:"status"`
	Createdat time.Time `gorm:"column:createdat;default:CURRENT_TIMESTAMP" json:"createdat"`
	Updatedat time.Time `gorm:"column:updatedat" json:"updatedat"`
	Deletedat time.Time `gorm:"column:deletedat" json:"deletedat"`
	Ext       string    `gorm:"column:ext" json:"ext"`
	Openid    string    `gorm:"column:openid" json:"openid"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}

